# --- 这是 Blowfish 主题的基本配置 ---

baseURL = "https://bailanwa.dpdns.org/"
languageCode = "zh-CN"
title = "我的新博客"
theme = "blowfish"

# ------------------------------------
# 你可以稍后再从 Blowfish 官网复制更完整的配置
# 但现在这些对于启动来说已经足够了
# ------------------------------------